### ISSUE TITLE
deleted

### ISSUE THREAD

**Issue by graysuit** [shadow578/YetAnotherVideoPlayer#10]
deleted

**Comment by shadow578** [comment]
Hi, theres generally nothing speaking agains you modifying the yavp's code to work with android 5 and below.
You'd just have to fork the repo and open it in android studio (just downloading the repo as a zip would not work because the app version names are based on the local git repo - so no repo, no version name).
Making the app work is _just_ a matter of changing the minSdkVersion in the build.gradle file to the version you'd like - and fix all the errors and/or bugs you encounter in doing so.
If you have any more questions regarding this, feel free to ask

**Comment by graysuit** [comment]
@shadow578 
Do you think I will be able use on android 5 by just decreasing version number ?
Here are details what I wanted to achieve, Can I achieve this ?

I want to make video protection software for my friend,
Who wants to sell his video courses safely only to those who have bought.

So for video protection, Our files will be encrypted,
And we don't want to decrypt and drop anywhere to play,
I wanted to decrypt video file in memory and then play it directly using stream.

I just need to able to play video from stream.
Other steps will be taken myself.

If i didn't make you understand well, then please you can also read this about content protection.
https://code.videolan.org/videolan/vlc-unity/-/issues/55

Please reply, I will add more details.
Thanks.

**Comment by shadow578** [comment]
I think it could work, tho i vaguely remember there being some hardships when i was trying to add support for android 5 and below, so probably not that easy to get working. I might be wrong tho.

In regards to your idea, it might just be easier for you to build your own app from the ground up, using exoplayer as a base.
The decryption could happen on the fly using a custom datasource (see  [here](https://stackoverflow.com/questions/38729220/reproducing-encrypted-video-using-exoplayer)).

**Comment by graysuit** [comment]
Ok Thanks brother,
I used these types of samples since more than 1 month,
But again I face tough hardship.
May be because I am a beginner in android development.
