### ISSUE TITLE
Why end this project

### ISSUE THREAD

**Issue by iBabu007** [shadow578/YetAnotherVideoPlayer#17]
Please sir don't drop this project.
It is too good. Concept is impressive.
But many bugs are available inside it.

**Comment by shadow578** [comment]
Hi Pranab009,

main reason is, as you mentioned, that there are many bugs. Combine that with the (for most parts) unstructured codebase, and you've got a lot of work just finding the cause of those bugs, let alone fix them.

Since i started going to University ~2 years ago, i just didn't have the time to work on YAVP any more.
