### ISSUE TITLE
latest version adds non-free dependencies?

### ISSUE THREAD

**Issue by IzzySoft** [shadow578/YetAnotherVideoPlayer#4]
I just noticed your new release added two non-free (i.e. non FOSS) dependencies: GMS and Android Vision. Are those really needed? Special "headache" in this context is the `CAMERA` permission together with `INTERNET`. I thought this is a video player?

Could you please explain what the `CAMERA` permission plus GMS are needed for by a video player? I'm a bit confused :wink: Also, abstention from non-FOSS components would be a good idea IMHO – they leave an otherwise good FOSS app "tainted".

Thanks!

PS: most likely an oversight, but the latest APK also comes with debugging enabled.

**Comment by shadow578** [comment]
Hi, 
first off, thanks for the feedback.

Those dependencies are for a feature I was experimenting with for a while.
The essential idea was to automatically pause the video once you look away from the screen (thus the Android Vision dependency). Take a look at [feature/autopause](https://github.com/shadow578/YetAnotherVideoPlayer/tree/master/app/src/main/java/de/shadow578/yetanothervideoplayer/feature/autopause) for more details.

This, however, turned out to be way more complicated to implement than I first thought it would be (thus the pause in developement during march and april). Also, testing showed that this idea isn't really practical too. I really just kinda forgot that it was still there when creating the release.

__TL;DR__: these dependencys will be removed once the autopause feature is removed, which will be in the next release.
<br/>
About the latest APK coming with debugging enabled: Do you know any resources/ posts / tutorials on how to properly export a apk from Android Studio. I followed [this](https://stackoverflow.com/a/19876060) guide, but it seems like it is somewhat outdated now.

**Comment by IzzySoft** [comment]
Thanks for the explanation! Yes, that would need the front cam, understood. But glad to hear those deps will be gone again with the next version!

As for Studio: Sorry, I'm not an Android dev so I cannot tell. I just noticed because my scanner informed me (disclosure: I've [added your app here](https://apt.izzysoft.de/fdroid/index/apk/de.shadow578.yetanothervideoplayer) to make it easier to access by us "privacy folks" who avoid Play Store and prefer sticking with FOSS; NonFreeDep & ApplicationDebuggable hints will show up there with the next sync in about 9 hours, but of course disappear with the version that has removed them).

**Comment by shadow578** [comment]
Check out the newest release.
It should have the gms dependencys removed 
Also, I think I figured out how to export the apk correctly. So the newest release now is actually a release and even correctly signed (at least I think :P)

**Comment by IzzySoft** [comment]
Thanks a lot – and I can confirm! My scanner just informed me to remove the AntiFeatures, and so I did. With the next sync tomorrow the warning will be gone from the listing. :green_heart:
